import { Slide } from '@/types/editor';

/**
 * Default showcase slides — shared between the editor's initial state
 * and the /demo page so both always display the same content.
 */
export const DEMO_SLIDES: Slide[] = [
    {
        id: 'demo-1',
        backgroundColor: '#0f172a',
        backgroundImage: '',
        backgroundVideo: '',
        backgroundType: 'color',
        background: '#0f172a',
        elements: [
            {
                id: 'demo-1-badge',
                type: 'text',
                content: '✦  Visual Slider Builder',
                x: 80,
                y: 130,
                style: {
                    fontSize: '12',
                    fontWeight: '600',
                    color: '#38bdf8',
                    letterSpacing: '1.5px',
                    textTransform: 'uppercase',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0 },
                    animate: { opacity: 1 },
                    transition: { duration: 0.5 },
                },
            },
            {
                id: 'demo-1-title',
                type: 'text',
                content: 'Modern Slider Pro',
                x: 80,
                y: 165,
                style: {
                    fontSize: 64,
                    fontWeight: '800',
                    color: '#f1f5f9',
                    lineHeight: 0.9,
                    letterSpacing: '-2px',
                },
                animation: {
                    name: 'Slide Up',
                    initial: { opacity: 0, y: 30 },
                    animate: { opacity: 1, y: 0 },
                    transition: { duration: 0.6, delay: 0.15 },
                },
            },
            {
                id: 'demo-1-sub',
                type: 'text',
                content: 'Drag-and-drop editor · Framer Motion animations · React',
                x: 80,
                y: 275,
                style: {
                    fontSize: '18',
                    color: '#94a3b8',
                    fontWeight: '400',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, y: 15 },
                    animate: { opacity: 1, y: 0 },
                    transition: { duration: 0.5, delay: 0.35 },
                },
            },
            {
                id: 'demo-1-btn',
                type: 'button',
                content: 'Open Editor →',
                x: 80,
                y: 340,
                style: {
                    fontSize: '14',
                    fontWeight: '600',
                    backgroundColor: '#3b82f6',
                    color: '#ffffff',
                    padding: '11px 26px',
                    borderRadius: '8px',
                    border: 'none',
                    cursor: 'pointer',
                    display: 'inline-block',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, scale: 0.92 },
                    animate: { opacity: 1, scale: 1 },
                    transition: { duration: 0.4, delay: 0.5 },
                },
            },
        ],
    },
    {
        id: 'demo-2',
        backgroundColor: '#1e1b4b',
        backgroundImage: '',
        backgroundVideo: '',
        backgroundType: 'color',
        background: '#1e1b4b',
        elements: [
            {
                id: 'demo-2-tag',
                type: 'text',
                content: 'EDITOR FEATURES',
                x: 80,
                y: 130,
                style: {
                    fontSize: '12',
                    fontWeight: '700',
                    color: '#a78bfa',
                    letterSpacing: '2px',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0 },
                    animate: { opacity: 1 },
                    transition: { duration: 0.4 },
                },
            },
            {
                id: 'demo-2-title',
                type: 'text',
                content: 'Build. Animate. Ship.',
                x: 80,
                y: 165,
                style: {
                    fontSize: 64,
                    fontWeight: '800',
                    color: '#ede9fe',
                    lineHeight: 1.15,
                    letterSpacing: '-1.5px',
                },
                animation: {
                    name: 'Slide Left',
                    initial: { opacity: 0, x: -50 },
                    animate: { opacity: 1, x: 0 },
                    transition: { duration: 0.55, delay: 0.1 },
                },
            },
            {
                id: 'demo-2-f1',
                type: 'text',
                content: '▸  Drag & drop canvas with snapping',
                x: 82,
                y: 270,
                style: { fontSize: '16', color: '#c4b5fd' },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, x: -20 },
                    animate: { opacity: 1, x: 0 },
                    transition: { duration: 0.4, delay: 0.25 },
                },
            },
            {
                id: 'demo-2-f2',
                type: 'text',
                content: '▸  Per-element entrance animations',
                x: 82,
                y: 308,
                style: { fontSize: '16', color: '#c4b5fd' },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, x: -20 },
                    animate: { opacity: 1, x: 0 },
                    transition: { duration: 0.4, delay: 0.38 },
                },
            },
            {
                id: 'demo-2-f3',
                type: 'text',
                content: '▸  Multi-slide management & layer panel',
                x: 82,
                y: 346,
                style: { fontSize: '16', color: '#c4b5fd' },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, x: -20 },
                    animate: { opacity: 1, x: 0 },
                    transition: { duration: 0.4, delay: 0.51 },
                },
            },
        ],
    },
    {
        id: 'demo-3',
        backgroundColor: '#052e16',
        backgroundImage: '',
        backgroundVideo: '',
        backgroundType: 'color',
        background: '#052e16',
        elements: [
            {
                id: 'demo-3-tag',
                type: 'text',
                content: 'NPM PACKAGE',
                x: 80,
                y: 130,
                style: {
                    fontSize: '12',
                    fontWeight: '700',
                    color: '#4ade80',
                    letterSpacing: '2px',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0 },
                    animate: { opacity: 1 },
                    transition: { duration: 0.4 },
                },
            },
            {
                id: 'demo-3-title',
                type: 'text',
                content: 'Embed Anywhere',
                x: 80,
                y: 165,
                style: {
                    fontSize: 64,
                    fontWeight: '800',
                    color: '#dcfce7',
                    lineHeight: 1.15,
                    letterSpacing: '-1.5px',
                },
                animation: {
                    name: 'Zoom In',
                    initial: { opacity: 0, scale: 0.8 },
                    animate: { opacity: 1, scale: 1 },
                    transition: { duration: 0.55, delay: 0.1 },
                },
            },
            {
                id: 'demo-3-code',
                type: 'box',
                content: "import { SliderRunner } from 'modern-slider-pro';",
                x: 80,
                y: 270,
                style: {
                    fontSize: '14',
                    fontFamily: 'monospace',
                    backgroundColor: 'rgba(0,0,0,0.45)',
                    color: '#86efac',
                    padding: '12px 20px',
                    borderRadius: '8px',
                    border: '1px solid rgba(74,222,128,0.2)',
                    whiteSpace: 'nowrap',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0, y: 10 },
                    animate: { opacity: 1, y: 0 },
                    transition: { duration: 0.4, delay: 0.3 },
                },
            },
            {
                id: 'demo-3-sub',
                type: 'text',
                content: 'Export slides as JSON · Render with <SliderRunner />',
                x: 80,
                y: 345,
                style: {
                    fontSize: '16',
                    color: '#86efac',
                    fontWeight: '400',
                },
                animation: {
                    name: 'Fade In',
                    initial: { opacity: 0 },
                    animate: { opacity: 1 },
                    transition: { duration: 0.4, delay: 0.5 },
                },
            },
        ],
    },
];
